all : codexhtml codexcss codexmd

codexcss :
	@echo "Quantum Universe reveal a story to be told"
	@node instance-groq-html.js

codexhtml:
	@echo "Crafting web's fabric with Quantum threads so bold"
	@node instance-groq-css.js

codexmd:
	@echo "initialisation du Quantum Universe"
	@node instance-groq-md.js

clean :
	@rm -rf /data/train/*	